# yaml file for package simple_grasping with rosnode "basic_grasping_perception"
############################################################################
gripper:
  tool_to_planning_frame: 0.175
  finger_depth: 0.020
  gripper_tolerance: 0.05
  approach:
    min: 0.115
    desired: 0.12
  retreat:
    min: 0.115
    desired: 0.12